# Generated by Django 2.1.7 on 2019-04-10 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 200자 입력가능', max_length=200)),
                ('contents', models.TextField()),
                ('timeSet', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
