# Generated by Django 2.1.7 on 2019-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingcontents',
            name='score',
            field=models.CharField(choices=[('first', 'star score 1'), ('second', 'star score 2'), ('third', 'star score 3'), ('fourth', 'star score 4'), ('fifth', 'star score 5')], default=True, max_length=1),
            preserve_default=False,
        ),
    ]
